.github/workflows/build.yml, Dockerfile
The Docker arguments that were specified before the FROM statement were always empty after the FROM statement. You can tell it's not working by the logs, and by the fact that the output images are the same size for `ros-base` vs `ros-desktop` https://hub.docker.com/repository/docker/rostooling/setup-ros-docker/tags?page=1
=> Actually install the extra apt packages

setup-ros.sh
Currently, the `rosbuild` user doesn't have its own home directory. A home directory is needed for many things to work.
(The CI is currently working because GitHub actions remap $HOME to `/github/home/`.)
=> Create home directory for user

Dockerfile
Now that these base images are actually installing the ROS 1 variants, we've discovered that they clobber the `catkin_pkg` installation. The only good solution we have is to install again over the top. The `python3-catkin-pkg` install is incompatible with the ROS 1 apt packages, so it can't coexist, but the pip version enables running colcon without issue.
Signed-off-by: Emerson Knapp <emerson.b.knapp@gmail.com>
=> Install catkin_pkg over the top of the ros installation

.github/workflows/build.yml, Dockerfile, setup-ros.sh
Clarify the build matrix for images, and enable Foxy (with its ros2-testing apt repo)
I think this probably needs an integration test before merging.
Signed-off-by: Emerson Knapp <eknapp@amazon.com>
=> Enable Foxy builds, using the ros2-testing repos

.github/workflows/build.yml, Dockerfile, setup-ros.sh
Our base images install `python3-rosdep`, but this is apparently incompatible with the `ros-kinetic-ros-core`/`ros-melodic-ros-core` packages (by installing `ros-kinetic-ros-core`/`ros-melodic-ros-core`, `python3-rosdep` gets removed).
In order to have a usable `rosdep` in our ROS1 images, the `python-rosdep` APT package needs to be installed.
=> Install python-rosdep for ROS1 images

setup-ros.sh
Recent versions of flake8 are incompatible with ament_flake8.
This prevents incompatible from being installed until the issue is
fixed in all combinations of ROS / ROS 2 distributions this repository
supports.
=> Only allow flake8<3.8 to be installed

.github/workflows/build.yml
This reverts commit c48308ce60421fcd3908a6a036669c01f106232d.
Currently the retry logic breaks docker push. Need to fix, verify, and test before using.
=> Revert "Add retry logic for docker push (#20)"

.github/workflows/build.yml
This reverts commit 64ff3b4a09bb274ac4e54e8d1edcd05c36ca56c2.
Unsure why there are CI failures so reverting all recent changes.
=> Revert "Fix parameter name warning (#21)"

Dockerfile, setup-ros.sh
Fixes #7 
According to the github action documentation, we should actually run all actions in containers as the root user - this is the recommended workflow. We originally chose non-root because its standard practice in other docker-based workflows, such as web applications.
From https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners
> Note: GitHub Actions must be run by the default Docker user (root). Ensure your Dockerfile does not set the USER instruction, otherwise you will not be able to access GITHUB_WORKSPACE
The above applies to also `GITHUB_ENV` and `GITHUB_PATH`, which are separate paths used by the `core.addPath` and `core.setEnv` commands from `@actions/core`. As of https://github.blog/changelog/2020-10-01-github-actions-depre …
=> Run as root user

setup-ros.sh
Latest version of action-ros-ci calls colcon coveragepy-result so it became a dependency for use in action-ros-ci
=> Install colcon-coveragepy-result

setup-ros.sh
For compatibility with Python2 and 3.5, the newest major version broke compatibility
=> Pin importlib-metadata to v2

.github/workflows/build.yml
This fixes the build by using released version of Foxy. The only reason we used testing was to enable Foxy builds before it was initially released.
`ros-foxy-desktop` build is not currently working in `ros2-testing`, which is why it couldn't be found by the build. 
See https://build.ros2.org/job/Fbin_uF64__desktop__ubuntu_focal_amd64__binary/76/ for the failing build and 
http://packages.ros.org/ros2-testing/ubuntu/dists/focal/main/binary-amd64/Packages to see that `ros-foxy-desktop` is not present (but `ros-foxy-ros-base` is).
Note https://github.com/ros2/build_farmer/issues/275 opened for this separate issue
=> Don't use testing repos anymore for Foxy since it is fully released and supported

.github/workflows/build.yml
It has reached EOL and will not be getting any updates. The already-created images are still on dockerhub, but there is no need to continue rebuilding the images
=> Remove eloquent

setup-ros.sh
This is expected to make the build go from red to green (the Xenial-based builds are failing)
See https://pip.pypa.io/en/stable/news/#id1 release notes for v21.0, which states that support for python 3.5 is dropped
See https://github.com/pypa/pip/issues/9515 for some more information
=> Do an intermediate upgrade to pip 20 before trying any further, so that xenial can pass and avoid an incompatible version

.github/workflows/build.yml, Dockerfile
The images will still exist on Dockerhub, but as Kinetic is EOL, no changes will occur, so the old images may continue to be used successfully. We do not need to build them anymore.
Additionally, kinetic are the builds that are currently failing in [the hourly](https://github.com/ros-tooling/setup-ros-docker/actions/runs/1831979647) - so removing them should fix that build up pretty good.
I know it might be a bit overloaded but I also kicked the scheduled build back to daily, there is no good reason i can think of to run it every hour.
=> Remove kinetic due to EOL

setup-ros.sh
For example, this was causing melodic/bionic images to get `python3-rosdep` ([which is not the right package for Bionic; should be `python-rosdep`](https://wiki.ros.org/melodic/Installation/Ubuntu#Installation.2FUbuntu.2FBinariesBuildDependencies.Dependencies_for_building_packages)), and thus `rosdep` thus wasn't found.
Signed-off-by: Christophe Bedard <bedard.christophe@gmail.com>
=> Fix typo in 'lsb_release' command name

setup-ros.sh
Follow latest instructions from https://docs.ros.org/en/rolling/Installation/Ubuntu-Install-Debians.html#setup-sources - and remove the "apt-key is deprecated" warning issues
=> Use ROS key from github, with keyring and signed-by, instead of apt-key

.github/workflows/build.yml
Iron all available now, can make base images for it
Galactic hit EOL in November so it is long past last sync. Melodic/Foxy are EOL this month but they still will have another sync, so we shouldn't remove yet.
=> Add Iron and remove Galactic

.github/workflows/build.yml
=> Install all rmw implementations

setup-ros.sh
Closes #60
Replaces #61 because CI for PRs from forks doesn't have access to secrets.
=> Pin empy version, bump other versions to match setup-ros

setup-ros.sh
Follow-up to #71.
We need to use the testing apt repo to get Jazzy binaries before Jazzy is officially released. See: https://docs.ros.org/en/jazzy/Installation/Ubuntu-Install-Debians.html#enable-required-repositories. Once Jazzy has been released, we can revert this.
=> Use ros2-testing repo for Jazzy before it's released

setup-ros.sh
Relates to #67 
This is similar to https://github.com/ros-tooling/setup-ros/pull/593. It updates the list of installed packages to use `apt` only, which matches the more recent installation instructions. I did this for Noble only, since it has the most problems with versions differing a lot between `apt` and `pip`, and I didn't want to risk breaking Humble and Iron. Therefore, for Jammy and older (which includes Humble and Iron), nothing should change.
Note that we used to install a lot of packages using `pip`. Some of those are included in `ros-dev-tools` with `apt`, and others were simply changed to be installed with `apt` instead of `pip` (like `python3-colcon-*`).
----
Steps to test this:
1. Build Docker image locally
* In this case, build the Noble `ros-rolling-ros-base` image
```
$ …
```
=> Prefer system packages over pip packages for Noble

setup-ros.sh
Closes #67
Follow-up to #73 for Jammy (22.04). The list of `apt` packages is basically just the same.
----
See PR description of #73 for commands and steps to build images locally and test with `action-ros-ci`.
Testing these images over at https://github.com/ros-tooling/action-ros-ci/pull/871:
* The `Test rosdep check/skip install options` job that has been failing for a long time now works:
* Before: https://github.com/ros-tooling/action-ros-ci/actions/runs/9130274663/job/25108392542?pr=871#step:4:6547
* Error: `E   TypeError: import_path() missing 1 required keyword-only argument: 'consider_namespace_packages'`
* After: https://github.com/ros-tooling/action-ros-ci/actions/runs/9133039538/job/25115696734#step:4:6328
* The `ROS 2 Docker` jobs pass and use versions of dependencies from …
=> Prefer system packages over pip packages for Jammy

.github/workflows/automerge.yml, Dockerfile, setup-ros.sh
Given our current colcon pins on focal, this happens
```
colcon_core.package_identification.python_setup_py': module 'importlib_metadata' has no attribute 'EntryPoints'
```
It's because the newest `setuptools` requires a newer version of `importlib_metadata`. We don't need to fix things for the newer version, the system version is old on Focal and that's fine, I just pin it back to a compatible version.
* While I'm changing this, update `automerge` action to pass, not sure exactly why but the old version isn't working properly anymore 🤷 
* And Docker is newer, so it doesn't like `ENV VAR VAL` now and prints a warning that you should do `ENV VAR=VAL` so I fixed that.
=> Pin setuptools version in focal because newer version is broken against our other pins

setup-ros.sh
fixes #77  
tested on
- humble,jammy,arm64
- humble,jammy  amd64
- jazzy,noble,amd64
See https://github.com/ros-tooling/setup-ros/pull/507
=> fix: remove libc++-* from jammy and above
